# Generated by Django 5.1 on 2024-09-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='id',
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='reply',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
